---
title: "Advent of code 2021 day 5"
description: |
  --- Day 5: Hydrothermal Venture ---
author:
  - name: Philippe Massicotte
    url: {}
date: 2021-12-05
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
file <- here("data/input/2021/05/01_input")

df <-
  read_delim(file, delim = "->", col_names = c("from", "to")) %>%
  mutate(across(everything(), str_squish)) %>%
  separate(from,
    into = c("x1", "y1"),
    sep = ",",
    convert = TRUE
  ) %>%
  separate(to,
    into = c("x2", "y2"),
    sep = ",",
    convert = TRUE
  )

df

is_diag <- function(x1, y1, x2, y2) {
  # browser()
  abs(x1 - x2) == abs(y1 - y2)
}

res <- df %>%
  rowid_to_column(var = "line") %>%
  mutate(line_type = case_when(
    x1 == x2 | y1 == y2 ~ "hv",
    is_diag(x1, y1, x2, y2) ~ "diag"
  )) %>%
  pivot_longer(
    -c(line, line_type),
    names_to = c(".value", "point"),
    names_pattern = "(.)(.)"
  ) %>%
  group_nest(line, line_type) %>%
  mutate(res = map2(data, line_type, function(df, line_type) {
    res <- df %>%
      mutate(xy = list(tibble(x = x[1]:x[2], y = y[1]:y[2]))) %>%
      select(-x, -y) %>%
      slice(1) %>%
      unnest(xy)
  }))

```

## Part 1
```{r}
## Part 1

res %>%
  filter(line_type == "hv") %>%
  unnest(res) %>%
  unite("xy", x:y) %>%
  count(xy, sort = TRUE) %>%
  filter(n >= 2) %>%
  nrow()
```

## Part 2

```{r}
res %>%
  unnest(res) %>%
  unite("xy", x:y) %>%
  count(xy, sort = TRUE) %>%
  filter(n >= 2) %>%
  nrow()
```

