---
title: "Advent of code 2020 day 7"
description: |
  --- Day 7: Handy Haversacks ---
author:
  - name: Philippe Massicotte
date: 12-12-2020
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/7

## Read the input data

```{r}
file <- here("data", "input", "day7_test.txt")

df <- read_lines(file) %>%
  enframe(name = "id", value = "raw_data") %>%
  mutate(bags = map(raw_data, function(raw_data) {
    str_split(raw_data, "contain|,") %>%
      unlist() %>%
      str_remove_all("bags|bag|\\.|\\d+") %>%
      str_squish() %>% 
      str_replace_all("\\W+", "_")
  })) %>%
  select(-raw_data)

df %>%
  unnest(bags) %>%
  rmarkdown::paged_table()
```

## Part 1

```{r}
library(igraph)

res <- df %>%
  mutate(res = map(bags, function(bags) {
    tibble(
      from = bags,
      to = lead(bags, 1)
    )
  })) %>%
  unnest(res) %>%
  select(-bags) %>%
  drop_na()

res <- res %>%
  select(-id) %>% 
  distinct()

res

g <- res %>% 
  graph_from_data_frame(directed = TRUE)

plot(g, layout = layout.fruchterman.reingold(g, niter=10000))
```


```{r}

# df %>% 
#   mutate(parent = head_while())

```

