---
title: "Advent of code 2015 day 06"
description: |
  --- Day 6: Probably a Fire Hazard ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
input <- read_lines(here("data", "input", "2015", "06_input"))

df <- tibble(input) %>%
  extract(input,
    into = c("action", "row_from", "col_from", "row_to", "col_to"),
    regex = "(turn on|turn off|toggle) (\\d+),(\\d+) through (\\d+),(\\d+)",
    convert = TRUE
  )
```

## Part 1

```{r}
lights <- function(action, row_from, col_from, row_to, col_to) {
  switch(action,
    "turn off" = m[row_from:row_to, col_from:col_to] <<- FALSE,
    "turn on" = m[row_from:row_to, col_from:col_to] <<- TRUE,
    "toggle" = m[row_from:row_to, col_from:col_to] <<-
      !m[row_from:row_to, col_from:col_to]
  )
}

m <- matrix(FALSE, nrow = 1000, ncol = 1000)
pwalk(
  list(df$action, df$row_from, df$col_from, df$row_to, df$col_to),
  lights
)

sum(m)
```

## Part 2

```{r}
lights <- function(action, row_from, col_from, row_to, col_to) {
  switch(action,
    "turn off" = m[row_from:row_to, col_from:col_to] <<-
      m[row_from:row_to, col_from:col_to] - 1,
    "turn on" = m[row_from:row_to, col_from:col_to] <<-
      m[row_from:row_to, col_from:col_to] + 1,
    "toggle" = m[row_from:row_to, col_from:col_to] <<-
      m[row_from:row_to, col_from:col_to] + 2
  )

  m[row_from:row_to, col_from:col_to] <<-
    pmax(m[row_from:row_to, col_from:col_to], 0)
}

m <- matrix(0, nrow = 1000, ncol = 1000)

pwalk(
  list(df$action, df$row_from, df$col_from, df$row_to, df$col_to),
  lights
)

sum(m)
```
