---
title: "Advent of code 2020 day 2"
description: |
  --- Day 2: Password Philosophy ---
author:
  - name: Philippe Massicotte
date: 12-10-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/2

## Read the input data

```{r read_input}
file <- here("data", "input", "day2.txt")

x <- read_lines(file) 

df <- tibble(x)

df
```

```{r}
df <- df %>% 
  separate(x, into = c("policy", "password"), sep = ":") %>% 
  mutate(across(where(is.character), str_squish)) %>% 
  separate(policy, into = c("min", "max", "letter"), sep = "-| ", convert = TRUE)

df
```

## Part 1

How many passwords are valid.

```{r}
df %>% 
  mutate(count = str_count(password, letter)) %>% 
  rowwise() %>% 
  filter(between(count, min, max)) %>% 
  rmarkdown::paged_table()
```

## Part 2

How many passwords are valid according to the new interpretation of the policies?

```{r}
df %>% 
  mutate(location_1 = str_sub(password, min, min)) %>% 
  mutate(location_2 = str_sub(password, max, max)) %>% 
  rowwise() %>% 
  filter((letter == location_1 | letter == location_2) & (location_1 != location_2)) %>% 
  rmarkdown::paged_table()
```

