---
title: "Advent of code 2015 day 07"
description: |
  --- Day 7: Some Assembly Required ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
input <- read_lines(here("data", "input", "2015", "07_input"))

int2bit <- function(x, nBits = 16) {
  tail(rev(as.numeric(intToBits(x))), nBits)
}

bit2int <- function(bin, x, y) {
  Reduce(function(x, y) x * 2 + y, bin)
}

bit2int(int2bit(123))
```



```{r}
make_function <- function(action) {
  switch(action,
    "AND" = "bit2int(int2bit(x) & int2bit(y))",
    "OR" = "bit2int(int2bit(x) | int2bit(y))",
    "RSHIFT" = "bitwShiftR(x, y)",
    "LSHIFT" = "bitwShiftL(x, y)",
    "NOT" = "bit2int(!int2bit(x))",
    "ASSIGN" = "return(x)"
  )
}

eval(parse(text = make_function("AND")), list(x = 1, y = 3))
eval(parse(text = make_function("OR")), list(x = 1, y = 3))
eval(parse(text = make_function("RSHIFT")), list(x = 10, y = 1))
eval(parse(text = make_function("LSHIFT")), list(x = 10, y = 1))
eval(parse(text = make_function("NOT")), list(x = 10))
eval(parse(text = make_function("ASSIGN")), list(x = 210))

df <- tibble(input) %>%
  mutate(lhs = str_match(input, "-> (.*)")[, 2]) %>%
  mutate(action = str_extract(input, "[A-Z]+")) %>%
  mutate(action = ifelse(is.na(action), "ASSIGN", action)) %>%
  rowwise() %>%
  mutate(f = make_function(action)) %>%
  ungroup() %>%
  rowid_to_column()

df

df <- df %>%
  mutate(input = str_remove(input, " -> .*")) %>%
  mutate(x = case_when(
    action %in% c("AND", "OR", "RSHIFT", "LSHIFT", "ASSIGN") ~ str_extract(input, "^[a-z]+|^\\d+"),
    action == "NOT" ~ str_extract(input, "[a-z]+$"),
    TRUE ~ NA_character_
  )) %>%
  mutate(y = case_when(
    action %in% c("AND", "OR", "RSHIFT", "LSHIFT") ~ str_extract(input, "[a-z]+$|\\d+$"),
  ))

lut <- df %>%
  select(lhs) %>%
  mutate(val = NA) %>%
  deframe()

lut <- lut[sort(names(lut))]
```

## Part 1

```{r}

`%notin%` <- Negate(`%in%`)

# queue <- df %>%
#   slice(89)

queue <- df

while (nrow(queue) >= 1) {
  rowid <-
    pmap_int(
      list(
        queue$rowid,
        queue$action,
        queue$f,
        queue$x,
        queue$y,
        queue$lhs
      ),
      .f = function(rowid, action, f, x, y, lhs) {
        x <- ifelse(str_detect(x, "[0-9]+"), parse_integer(x), lut[x])
        y <- ifelse(str_detect(y, "[0-9]+"), parse_integer(y), lut[y])

        param <- list(x = x, y = y)

        if ((action %in% c("AND", "OR", "RSHIFT", "LSHIFT")) &
          !is.na(x) & !is.na(y)) {
          res <- eval(parse(text = f), param)
          lut[lhs] <<- res
          return(rowid)
        }

        if ((action %in% c("ASSIGN", "NOT")) & !is.na(x)) {
          res <- eval(parse(text = f), param)
          lut[lhs] <<- res
          return(rowid)
        }

        return(NA_integer_)
      }
    )

  rowid <- na.omit(rowid)
  # cat("Removing", rowid, "\n")
  queue <- queue %>%
    filter(rowid %notin% {{ rowid }})
}
```


## Part 2
