---
title: "Advent of code 2021 day 11"
description: |
  --- Day 11: Dumbo Octopus ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}

flash_around <- function(rr, cc) {
  if (m[rr, cc] == 10) {
    m[rr, cc] <<- 0
    flashed[rr, cc] <<- TRUE
    time_flashed <<- time_flashed + 1

    # browser()

    # Top
    if (rr > 1) {
      rrr <- rr - 1
      ccc <- cc

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Top right
    if (rr > 1 & cc < ncol(m)) {
      rrr <- rr - 1
      ccc <- cc + 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Right
    if (cc < ncol(m)) {
      rrr <- rr
      ccc <- cc + 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Bottom right
    if (rr < nrow(m) & cc < ncol(m)) {
      rrr <- rr + 1
      ccc <- cc + 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Bottom
    if (rr < nrow(m)) {
      rrr <- rr + 1
      ccc <- cc

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Bottom left
    if (rr < nrow(m) & cc > 1) {
      rrr <- rr + 1
      ccc <- cc - 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Left
    if (cc > 1) {
      rrr <- rr
      ccc <- cc - 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }

    # Top left
    if (rr > 1 & cc > 1) {
      rrr <- rr - 1
      ccc <- cc - 1

      if (m[rrr, ccc] < 10 & !flashed[rrr, ccc]) {
        m[rrr, ccc] <<- m[rrr, ccc] + 1
        flash_around(rrr, ccc)
      }
    }
  } else {
    return(0)
  }
}

loop <- function(df) {
  # browser()
  m <<- m + 1
  flashed <<- m == 10

  res <- pmap(list(df$rr, df$cc), flash_around)

  if (all(flashed)) {
    return(TRUE)
  }

  return(FALSE)
}
```

## Part 1

```{r}
m <- read_lines(here("data/input/2021/11_input")) %>%
  strsplit("") %>%
  map(., as.numeric) %>%
  do.call(rbind, .)

df <- crossing(
  rr = 1:nrow(m),
  cc = 1:ncol(m),
  step = 1:100
) %>%
  mutate(time_visited = 0) %>%
  group_nest(step)

time_flashed <- 0

res <- df %>%
  mutate(fully_flashed = map_lgl(data, loop))

time_flashed
```

## Part 2

```{r}
m <- read_lines(here("data/input/2021/11_input")) %>%
  strsplit("") %>%
  map(., as.numeric) %>%
  do.call(rbind, .)

fully_flashed <- FALSE
times <- 0

while (!fully_flashed) {

  # browser()
  indices <- crossing(
    rr = 1:nrow(m),
    cc = 1:ncol(m)
  )

  fully_flashed <- loop(indices)

  times <- times + 1
}

times
```
