---
title: "Advent of code 2020 day 5"
description: |
  --- Day 5: Binary Boarding ---
author:
  - name: Philippe Massicotte
date: 12-11-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/5

## Read the input data

```{r read_input}
file <- here("data", "input", "day5.txt")

x <- read_lines(file)

head(x, 20)
```

Here I am going to create a recursive function that splits the index vector into the upper or lower half.

```{r}
find_index <- function(letter, index_range) {

  # F: the lower half
  # B: the upper half

  l <- str_sub(letter, 1, 1)

  if (length(index_range) == 1) {
    return(index_range)
  }

  if (l == "F" | l == "L") {
    start <- 1
    end <- ceiling(length(index_range) / 2)
    index_range <- index_range[start:end]
  } else if (l == "B" | l == "R") {
    start <- floor((length(index_range) / 2) + 1)
    end <- length(index_range)
    index_range <- index_range[start:end]
  }

  find_index(str_sub(letter, 2, end), index_range)
}
```

## Part 1

Find the row and column numbers.

```{r}
find_seat_id <- function(x, row_range, col_range) {

  i <- str_sub(x, 1, 7)
  i <- find_index(x, index_range)

  j <- str_sub(x, -3, -1)
  j <- find_index(j, col_range)

  return(i * 8 + j)
}
```

## Get the seat IDs

```{r}
index_range <- 0:127
col_range <- 0:7

# Try with the test data to see if it works
find_seat_id("FBFBBFFRLR", row_range, col_range)
find_seat_id("BFFFBBFRRR", row_range, col_range)
find_seat_id("FFFBBBFRRR", row_range, col_range)
find_seat_id("BBFFBBFRLL", row_range, col_range)
```

## Extract all the seat IDs

```{r}
seatids <- map_dbl(
  x,
  find_seat_id,
  row_range = row_range,
  col_range = col_range
)

head(seatids, 20)
```

Find the highest seat ID.

```{r}
max(seatids)
```

## Part 2

What is the ID of your seat?

```{r}
seatids_sorted <- sort(seatids)

i <- which(diff(seatids_sorted) != 1)

seatids_sorted[i] + 1 # Do not forget, it is 0 based!
```
