---
title: "Advent of code 2021 day 12"
description: |
  --- Day 12: Passage Pathing ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
df <- read_lines(here("data/input/2021/12_input")) %>%
  strsplit("-") %>%
  map(., ~ if_else(.[1] == "end" | .[2] == "start", list(rev(.)), list(.))) %>%
  flatten() %>%
  enframe() %>%
  unnest_wider(value) %>%
  select(parent = 2, child = 3) %>%
  drop_na()

lut <- df %>%
  deframe()

lut2 <- lut[names(lut) != "start" & lut != "end"]

lut2 <- setNames(names(lut2), lut2)
lut <- c(lut, lut2)

check_duplicated <- function(p, nmax = 1) {
  lc <- p[tolower(p) == p & p != "end"]
  tc <- table(lc)

  any(tc > nmax) | length(tc[tc > 1]) > 1
}

build_path <- function(path, nmax) {

  if (tail(path, 1) == "end") {
    return(data.frame(path = toString(unname(path))))
  }

  if (is.na(lut[tail(path, 1)])) {
    return()
  }

  next_points <- unname(lut[names(lut) == tail(path, 1)])
  next_path <- map(next_points, ~ c(path, .x))

  next_path <- next_path[!map_lgl(next_path, check_duplicated, nmax = nmax)]

  if (length(next_path) == 0) {
    return()
  }

  res <- map_df(unname(next_path), build_path, nmax = nmax)

  return(res)
}

s <- lut[names(lut) == "start"]
```

## Part 1

```{r}
res <- map_df(unname(s), build_path, nmax = 1)
nrow(res)
```

## Part 2

```{r}
res <- map_df(unname(s), build_path, nmax = 2)
nrow(res)
```
