---
title: "Advent of code 2020 day 1"
description: |
  --- Day 1: Report Repair ---
author:
  - name: Philippe Massicotte
date: 12-10-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/1

## Read the input data

```{r read_input}
file <- here("data", "input", "day1.txt")

x <- read_lines(file) %>% 
  parse_number()

x
```

## Find all combinations of 2 elements

```{r}
m <- 3

col_names <- paste0("x", 1:m)

df <- combn(x, m = m) %>% 
  t() %>% 
  as_tibble() %>% 
  set_names(col_names)

df
```

## Calculate the sum

```{r}
df <- df %>% 
  mutate(total = rowSums(.))

df
```

## Extract the line with the sum equal to 2020

```{r}
df <- df %>% 
  filter(total == 2020)

df
```

## Calculate the product

```{r}
df <- df %>% 
  rowwise() %>% 
  mutate(total = prod(c_across(starts_with("x"))))

df
```

**Answer:** `r format(pull(df, total), scientific = FALSE)`

