---
title: "Advent of code 2020 day 4"
description: |
  --- Day 4: Passport Processing ---
author:
  - name: Philippe Massicotte
date: 12-11-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/4

## Read the input data

```{r read_input}
file <- here("data", "input", "day4.txt")

x <- read_lines(file)

xx <- str_split(x, " ") %>%
  unlist() %>%
  paste(collapse = " ") %>%
  str_split("  ") %>%
  unlist()

df <- xx %>%
  str_split(" ") %>%
  set_names(1:length(.)) %>%
  # unlist() %>%
  enframe(name = "passport") %>%
  mutate(passport = parse_number(passport)) %>%
  unnest(value) %>%
  separate(value, into = c("field", "value"), sep = ":") %>%
  arrange(passport)
```

This gives us a total of 291 passports.

```{r}
df %>%
  pivot_wider(names_from = field, values_from = value) %>%
  rmarkdown::paged_table()
```

# Part 1

```{r}
expected_fields <- c(
  "byr",
  "iyr",
  "eyr",
  "hgt",
  "hcl",
  "ecl",
  "pid"
)

filtered_passport <- df %>%
  group_by(passport) %>%
  filter(all(expected_fields %in% field)) %>%
  ungroup()

filtered_passport %>%
  pivot_wider(names_from = field, values_from = value) %>%
  rmarkdown::paged_table()
```

**Answer:** `r length(unique(filtered_passport$passport))`

## Part 2

The second part consists in filtering the remaining passports with stricter rules.

```{r}
filtered_passport <- filtered_passport %>%
  pivot_wider(names_from = field, values_from = value) %>% 
  mutate(across(c(byr, iyr, eyr), parse_number))

filtered_passport <- filtered_passport %>%
  filter(between(byr, 1920, 2002)) %>%
  filter(between(iyr, 2010, 2020)) %>%
  filter(between(eyr, 2020, 2030)) %>%
  filter(str_detect(hgt, "^\\d+(cm|in)$")) %>%
  extract(
    hgt,
    into = c("hgt", "hgt_unit"),
    regex = "(\\d+)(.*)",
    convert = TRUE
  ) %>%
  filter((between(hgt, 150, 193) & hgt_unit == "cm") |
    (between(hgt, 59, 76) & hgt_unit == "in")) %>% 
  filter(str_detect(hcl, "^#[0-9a-f]{6}")) %>% 
  filter(ecl %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")) %>% 
  filter(str_detect(pid, "^\\d{9}$")) 

filtered_passport %>%
  rmarkdown::paged_table()
```

**Answer:** `r nrow(filtered_passport)`
