---
title: "Advent of code 2021 day 13"
description: |
  --- Day 13: Transparent Origami ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
file <- here("data", "input", "2021", "13_input")

dat <- read_lines(file)
idat <- max(which(str_starts(dat, "\\d")))

folds <-
  read_delim(
    file,
    skip = idat,
    col_names = c("along", "pos"),
    delim = "="
  ) %>%
  mutate(along = str_extract(along, "x|y"))

dots <- read_delim(file, col_names = c("x", "y"), n_max = idat) %>%
  mutate(across(c(x, y), ~ . + 1))

n_col <- max(dots$x)
n_row <- max(dots$y)

m <- matrix(NA, nrow = n_row, ncol = n_col)

m[cbind(dots$y, dots$x)] <- TRUE

fold <- function(m, pos, along = c("y", "x")) {

  if (along == "y") {
    m1 <- m[1:pos, ]
    m2 <- m[nrow(m):(pos + 2), ]
    m3 <- complete_mat(m1, m2, along)
    m <- m3[[1]] | m3[[2]]
  } else if (along == "x") {
    m1 <- m[, 1:pos]
    m2 <- m[, ncol(m):(pos + 2)]
    m <- m1 | m2
  }

  return(m)
}

complete_mat <- function(m1, m2, along) {
  if (along == "y") {
    if (nrow(m1) > nrow(m2)) {
      n_diff <- nrow(m1) - nrow(m2)
      m2 <- rbind(matrix(FALSE, nrow = n_diff, ncol = ncol(m2)), m2)
    }
    if (nrow(m1) < nrow(m2)) {
      n_diff <- nrow(m2) - nrow(m1)
      m1 <- rbind(matrix(FALSE, nrow = n_diff, ncol = ncol(m1)), m1)
    }
  } else if (along == "x") {
    if (ncol(m1) > ncol(m2)) {
      n_diff <- ncol(m1) - ncol(m2)
      m2 <- cbind(matrix(FALSE, ncol = n_diff, nrow = nrow(m2)), m2)
    }
    if (ncol(m1) < ncol(m2)) {
      n_diff <- ncol(m2) - ncol(m1)
      m1 <- cbind(matrix(FALSE, ncol = n_diff, nrow = nrow(m1)), m1)
    }
  }

  list(m1, m2)
}
```

## Part 1

```{r}
res <- folds %>%
  slice(1) %>%
  mutate(m = list(fold(m, pos, along)))

sum(res$m[[1]], na.rm = TRUE)
```


## Part 2

```{r}
for (i in 1:nrow(folds)) {
  m <<- fold(m, folds$pos[[i]], folds$along[[i]])
}
```

```{r}
library(terra)
r <- rast(m)
plot(r, asp = 0.1, bty = "n", axes = FALSE)
```


