---
title: "Advent of code 2015 day 09"
description: |
  --- Day 9: All in a Single Night ---
author:
  - name: Philippe Massicotte
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
input <- read_lines(here("data/input/2015/09_input"))

df <- tibble(input) %>%
  extract(
    input,
    into = c("from", "to", "distance"),
    regex = "(.*) to (.*) = (\\d+)",
    convert = TRUE
  )

lut <- df %>%
  rowwise() %>%
  mutate(path = list(sort(c(from, to)))) %>%
  select(-from, -to) %>%
  hoist(path, "from" = 1, "to" = 2)

cities <- unique(c(df$from, df$to))

res <-
  gtools::permutations(length(cities), length(cities), cities) %>%
  t() %>%
  as.data.frame() %>%
  as.list() %>%
  enframe() %>%
  slice(1:(nrow(.) / 2)) %>%
  mutate(pairs = map(value, ~ compact(
    slider::slide(., ~ sort(.x), .after = 1, .complete = TRUE)
  ))) %>%
  unnest(pairs) %>%
  hoist(pairs, "from" = 1, "to" = 2)

res <- res %>%
  inner_join(lut) %>%
  group_by(name) %>%
  summarise(total_distance = sum(distance))
```

## Part 1

```{r}
res %>%
  filter(total_distance == min(total_distance)) %>%
  pull(total_distance)
```

## Part 2

```{r}
res %>%
  filter(total_distance == max(total_distance)) %>%
  pull(total_distance)
```
