---
title: "Advent of code 2021 day 9"
description: |
  --- Day 9: Smoke Basin ---
author:
  - name: Philippe Massicotte
    url: {}
date: 2021-12-09
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)

# file <- "~/Desktop/input"
file <- here("data/input/2021/09")
m <- as.matrix(read_fwf(file, fwf_widths(rep(1, 100))))

low_point <- function(x, y, m) {
  r <- NULL
  l <- NULL
  d <- NULL
  u <- NULL

  max_x <- nrow(m)
  max_y <- ncol(m)

  if (x > 1) {
    l <- m[x, y] < m[x - 1, y]
  }
  if (y > 1) {
    u <- m[x, y] < m[x, y - 1]
  }

  if (x < max_x) {
    r <- m[x, y] < m[x + 1, y]
  }
  if (y < max_y) {
    d <- m[x, y] < m[x, y + 1]
  }

  if (all(c(r, l, u, d))) {
    return(list(x = x, y = y))
  } else {
    return(NULL)
  }
}

indices <- crossing(x = seq_len(nrow(m)), y = seq_len(ncol(m)))

result <- map2_dfr(indices$x, indices$y, low_point, m)

sum(m[cbind(result$x, result$y)] + 1)

# Part 2 ------------------------------------------------------------------

visited <- m == 9

low_point <- function(x, y) {
  if (visited[x, y]) {
    return(NULL)
  }
  visited[x, y] <<- TRUE

  value <- m[x, y]
  if (value == 9) {
    return(NULL)
  }

  around <- tibble(x = x, y = y, v = value)

  # Recurse until we reach a wall/9
  if (x < nrow(m)) {
    around <- bind_rows(around, low_point(x + 1, y))
  }
  if (y < ncol(m)) {
    around <- bind_rows(around, low_point(x, y + 1))
  }
  if (x > 1) {
    around <- bind_rows(around, low_point(x - 1, y))
  }
  if (y > 1) {
    around <- bind_rows(around, low_point(x, y - 1))
  }

  return(around)
}

res <- map2(result$x, result$y, low_point)
res %>%
  map_dbl(nrow) %>%
  sort(decreasing = TRUE) %>%
  head(3) %>%
  prod()
```


