---
title: "Advent of code 2020 day 6"
description: |
  --- Day 6: Custom Customs ---
author:
  - name: Philippe Massicotte
date: 12-12-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

https://adventofcode.com/2020/day/6

## Read the input data

```{r}
file <- here("data", "input", "day6.txt")

df <- read_file(file)

df <- df %>% 
  str_split("\n\n") %>% 
  unlist() %>% 
  set_names(1:length(.)) %>% 
  enframe(name = "group", value = "question") %>% 
  separate_rows(question, sep = "\n") %>% 
  rowid_to_column(var = "person_id")

df %>% 
  rmarkdown::paged_table()
```

## Part 1

Count the number of unique questions per group.

```{r}
n <- df %>% 
  mutate(question_splited = str_split(question, "")) %>% 
  unnest(question_splited) %>% 
  group_by(group) %>% 
  distinct(question_splited) %>% 
  summarise(n = n()) %>% 
  pull(n)

head(n, 20)
```

**Answer:** `r sum(n)`

## Part 2

Count the number of questions that have been answered by everyone in each group.

```{r}
n <- df %>% 
  mutate(question_splited = str_split(question, "")) %>% 
  unnest(question_splited) %>% 
  group_by(group) %>% 
  mutate(n_person_in_group = n_distinct(person_id)) %>% 
  add_count(question_splited) %>% 
  filter(n_person_in_group == n) %>% 
  distinct(group, question_splited, n) %>% 
  summarise(n = n()) %>% 
  pull(n)


head(n, 20)
```

**Answer:** `r sum(n)`
