---
title: "Advent of code 2021 day 8"
description: |
  --- Day 8: Seven Segment Search ---
author:
  - name: Philippe Massicotte
    url: {}
date: 2021-12-08
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
string_sort <- function(x) {
  unname(sapply(x, function(i) {
    paste(sort(
      unlist(strsplit(i, ""))
    ), collapse = "")
  }))
}


where <- function(v, x) {
  map_lgl(v, x = x, function(v, x) {
    all(str_split(x, "")[[1]] %in% str_split(v, "")[[1]])
  })
}

decode <- function(v) {
  one <- v[nchar(v) == 2]
  four <- v[nchar(v) == 4]
  seven <- v[nchar(v) == 3]
  eight <- v[nchar(v) == 7]

  n <- nchar(v)

  three <- v[n == 5 & where(v, one)]
  nine <- v[n == 6 & where(v, four)]
  zero <-
    v[n == 6 & where(v, one) & where(v, seven) & !where(v, four)]
  six <- v[n == 6 & !where(v, zero) & !where(v, nine)]
  five <-
    paste0(intersect(str_split(six, "")[[1]], str_split(nine, "")[[1]]), collapse = "")

  two <-
    setdiff(v, c(one, three, four, five, six, seven, eight, nine, zero))

  lut <- 0:9
  lut <- set_names(lut, c(zero, one, two, three, four, five, six, seven, eight, nine))


  return(lut)
}


df <-
  read_delim(
    here("data/input/2021/08"),
    delim = "|",
    col_names =  c("input", "output")
  ) %>%
  mutate(across(where(is.character), str_squish)) %>%
  mutate(across(where(is.character), str_split, pattern = " ")) %>%
  mutate(input = map(input, string_sort)) %>%
  mutate(output = map(output, string_sort))
```

## Part 1

```{r}
df %>%
  mutate(easy_digits = map_int(output, ~ sum(str_count(.) %in% c(2, 4, 3, 7)))) %>%
  pull(easy_digits) %>%
  sum()
```


## Part 2

```{r}
df %>%
  mutate(lut = map(input, decode)) %>%
  mutate(number = map2_chr(output, lut, ~paste(..2[..1], collapse = ""))) %>%
  mutate(number = parse_number(number)) %>%
  pull(number) %>%
  sum()
```


